version: '3'
services:
    stored_diff:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: stored_diff
        environment:
            DEVELOP_DNS: 
            STAGING_DNS: 
            PRODUCTION_DNS:
        ports:
            - "8080:8000"
        volumes:
            - ./:/app/
        command: . start.sh
        restart: always

